### ISSUE TITLE
Backport 1.19.3 to 1.19.2

### ISSUE THREAD

**Issue by itsdinkd** [the-glitch-network/plymouth-fabric#21]
### Module to add this to?

Anti XRay

### What would you like to be added?

Backport latest 1.19.3 version to 1.19.2

### Additional context?

1.19.3 is not widely used due to the small mod presence since this .3 update was quite large. Many modpacks, mine included, are still on 1.19.2, as are players.

**Comment by KJP12** [comment]
Backporting the 1.19.3 branch's changes most likely won't affect you; you should be fine as long as you're not running the latest Quilt 0.18.1 betas or a select set of mods.

I will still backport the applicable changes a bit later tho, if you are affected by either of the two cases.

**Comment by Ampflower** [comment]
v0.0.0 has been published with the relevant changes backported from 1.19.3.
